# deploy_config.yaml
# Sharpa Hand In-Hand rotation policy config for Windows Isaac Sim deployment

action_scale: 0.041666666666666664
clip_obs: 5.0

# 22-DoFs default joint pose (in degrees)
default_angles_deg: [
  95.12771,
  -3.11244,
  14.81626,
  -1.03493,
  12.23986,
  65.21091,
  6.1133,
  15.58495,
  5.90325,
  31.74149,
  -0.95812,
  41.88173,
  12.844,
  31.72383,
  9.84458,
  35.22366,
  18.02839,
  10.9712,
  68.30895,
  7.99151,
  5.89626,
  5.89875
]

# Joint order mapping
joint_names: [
  "right_thumb_CMC_FE",
  "right_thumb_CMC_AA",
  "right_thumb_MCP_FE",
  "right_thumb_MCP_AA",
  "right_thumb_IP",
  "right_index_MCP_FE",
  "right_index_MCP_AA",
  "right_index_PIP",
  "right_index_DIP",
  "right_middle_MCP_FE",
  "right_middle_MCP_AA",
  "right_middle_PIP",
  "right_middle_DIP",
  "right_ring_MCP_FE",
  "right_ring_MCP_AA",
  "right_ring_PIP",
  "right_ring_DIP",
  "right_pinky_CMC",
  "right_pinky_MCP_FE",
  "right_pinky_MCP_AA",
  "right_pinky_PIP",
  "right_pinky_DIP"
]
